blank_issues_enabled: false
contact_links:
  - name: Meilisearch Project Issues
    url: https://github.com/meilisearch/meilisearch/issues
    about: Please report Meilisearch issues here
  - name: Meilisearch Documentation Issues
    url: https://github.com/meilisearch/documentation/issues
    about: Please report documentation issues here
